import { Component } from '@angular/core';
import { DocPage } from '../shared/doc-page';
import { CodeBlock } from '../shared/code-block';

@Component({
  selector: 'migrations-page',
  standalone: true,
  imports: [DocPage, CodeBlock],
  template: `
    <doc-page eyebrow="Step 2" title="Run Migrations" lead="Convert your TypeScript schema to SQL and execute it against Supabase. All statements are idempotent — re-running is always safe.">

      <h2>What the generated SQL looks like</h2>
      <p>When you call <code>preview()</code> or <code>download()</code>, the output is ready to paste into the Supabase SQL Editor:</p>
      <code-block lang="sql" [code]="sqlPreview" />

      <p>Every policy is preceded by <code>DROP POLICY IF EXISTS</code>, so running this SQL again never fails with <em>"policy already exists"</em>.</p>

      <h2>Step A — Preview &amp; copy SQL (no keys needed)</h2>
      <p>An <code>AdminMigrationComponent</code> checks migration status on load and shows pending SQL automatically — no button click required.</p>
      <code-block lang="ts" filename="admin-migration.component.ts" [code]="adminCode" />

      <h2>Step B — Run automatically on app startup</h2>
      <p>Pass your migrations to <code>provideSaqlySupabase</code>. They run once on startup and are tracked automatically. Only new (not-yet-applied) migrations run; already-applied ones are silently skipped.</p>
      <code-block lang="ts" filename="app.config.ts" [code]="autoCode" />

      <code-block lang="bash" [code]="logCode" />

      <h2>Use Step A or B — or both</h2>
      <table>
        <thead><tr><th>Scenario</th><th>Recommendation</th></tr></thead>
        <tbody>
          <tr><td>Dev / staging — see SQL before it runs</td><td>Step A</td></tr>
          <tr><td>Production — run migrations silently on deploy</td><td>Step B</td></tr>
          <tr><td>Both — status in UI + auto-run on startup</td><td>Step A + B</td></tr>
        </tbody>
      </table>

      <h2>Execution modes</h2>
      <table>
        <thead><tr><th>What you provide</th><th>How migrations run</th></tr></thead>
        <tbody>
          <tr><td><code>managementKey</code></td><td>Supabase Management API — no setup required</td></tr>
          <tr><td><code>serviceRoleKey</code> only</td><td><code>exec_sql</code> RPC with service-role client</td></tr>
          <tr><td>Neither</td><td><code>exec_sql</code> RPC with anon client — run <code>MigrationRunner.setupSql()</code> once first</td></tr>
        </tbody>
      </table>

      <h2>Grants — automatically included</h2>
      <p>The generated SQL automatically includes <code>GRANT</code> statements derived from your policies.</p>
      <table>
        <thead><tr><th>Policy operation</th><th>SQL privileges granted</th></tr></thead>
        <tbody>
          <tr><td><code>select</code></td><td><code>SELECT</code></td></tr>
          <tr><td><code>insert</code></td><td><code>INSERT, SELECT</code></td></tr>
          <tr><td><code>update</code></td><td><code>UPDATE, SELECT</code></td></tr>
          <tr><td><code>delete</code></td><td><code>DELETE, SELECT</code></td></tr>
          <tr><td><code>all</code></td><td><code>SELECT, INSERT, UPDATE, DELETE</code></td></tr>
        </tbody>
      </table>

      <h2><code>MigrationDefinition</code></h2>
      <code-block lang="ts" [code]="migDefCode" />

      <h2>Schema alterations</h2>
      <p>When a table already exists and you need to change its structure, create a <strong>new</strong> <code>MigrationDefinition</code> using <code>alter()</code>. No SQL knowledge needed.</p>
      <code-block lang="ts" [code]="alterCode" />
      <code-block lang="sql" [code]="alterSql" />

      <table>
        <thead><tr><th>Method</th><th>SQL</th></tr></thead>
        <tbody>
          <tr><td><code>.addColumn(name, field)</code></td><td><code>ADD COLUMN IF NOT EXISTS …</code></td></tr>
          <tr><td><code>.dropColumn(name)</code></td><td><code>DROP COLUMN IF EXISTS …</code></td></tr>
          <tr><td><code>.renameColumn(old, new)</code></td><td><code>RENAME COLUMN … TO …</code></td></tr>
        </tbody>
      </table>
    </doc-page>
  `,
})
export class MigrationsPage {
  readonly sqlPreview = `-- Setup
create or replace function exec_sql(sql_query text)
returns json language plpgsql security definer as $$
begin
  execute sql_query;
  return '{"success": true}'::json;
exception when others then
  return json_build_object('error', sqlerrm);
end;
$$;

grant execute on function exec_sql(text) to anon, authenticated;

-- Migration: create-products-table

-- Tables
create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  price integer not null,
  stock integer default 0,
  description text,
  created_at timestamp with time zone default now()
);

-- Row Level Security
alter table public.products enable row level security;

-- Policies
drop policy if exists "Anyone can read products" on public.products;
create policy "Anyone can read products"
on public.products
for SELECT
to anon, authenticated
using (true);

-- Grants
grant usage on schema public to anon, authenticated;
grant SELECT, INSERT on table public.products to anon, authenticated;
grant usage, select on sequence public.products_id_seq to anon, authenticated;`;

  readonly adminCode = `import { Component, OnInit, signal } from '@angular/core';
import { injectMigration, MigrationRunner, MigrationRunResult } from 'ngx-saqly-supabase';
import { productsMigration } from '../schema/product';

const ALL_MIGRATIONS = [productsMigration];

@Component({
  selector: 'app-admin-migration',
  standalone: true,
  template: \`
    @if (setupReady() === false) {
      <div>
        <strong>⚠ One-time setup required</strong>
        <pre>{{ setupSql }}</pre>
        <button (click)="copySetupSql()">{{ copied() ? '✓ Copied!' : 'Copy SQL' }}</button>
        <button (click)="recheckSetup()">I've run it — re-check</button>
      </div>
    }

    @if (!loading() && pendingCount() > 0) {
      <pre>{{ sql() }}</pre>
    }
  \`,
})
export class AdminMigrationComponent implements OnInit {
  private readonly migration = injectMigration();

  readonly setupSql = MigrationRunner.setupSql();
  setupReady   = signal<boolean | null>(null);
  copied       = signal(false);
  loading      = signal(true);
  sql          = signal('');
  pendingCount = signal(0);

  async ngOnInit(): Promise<void> {
    this.setupReady.set(await this.migration.checkSetup());
    await this.loadPending();
  }

  async recheckSetup(): Promise<void> {
    this.setupReady.set(await this.migration.checkSetup());
    await this.loadPending();
  }

  copySetupSql(): void {
    navigator.clipboard.writeText(this.setupSql).then(() => {
      this.copied.set(true);
      setTimeout(() => this.copied.set(false), 2000);
    });
  }

  private async loadPending(): Promise<void> {
    this.loading.set(true);
    const pending = await this.migration.getPending(ALL_MIGRATIONS);
    this.pendingCount.set(pending.length);
    this.sql.set(await this.migration.previewMany(ALL_MIGRATIONS));
    this.loading.set(false);
  }
}`;

  readonly autoCode = `provideSaqlySupabase({
  url: environment.supabaseUrl,
  key: environment.supabaseAnonKey,
  migrations: [
    productsMigration,            // ← skipped if already applied
    addStockToProductsMigration,  // ← runs only once, then tracked
  ],
})`;

  readonly logCode = `[ngx-supabase] ✓ Migration "create-products-table" applied
[ngx-supabase] ✓ Migration "add-stock-to-products" applied`;

  readonly migDefCode = `import { MigrationDefinition } from 'ngx-saqly-supabase';

export const productsMigration: MigrationDefinition = {
  name: 'create-products-table',  // unique name — used for tracking
  tables: [ProductsTable],        // CREATE TABLE IF NOT EXISTS
  alterations: [],                // ALTER TABLE statements
  relations: [],                  // foreign key constraints
  rls: [ProductsTable],           // enable RLS
  policies: [ReadPolicy, InsertPolicy, UpdatePolicy, DeletePolicy],
};`;

  readonly alterCode = `import { alter, field, MigrationDefinition } from 'ngx-saqly-supabase';
import { ProductsTable } from './product';

export const addStockToProductsMigration: MigrationDefinition = {
  name: 'add-stock-to-products',
  alterations: [
    alter(ProductsTable).addColumn('stock', field.integer().default('0')),
  ],
};

export const addDescriptionMigration: MigrationDefinition = {
  name: 'add-description-to-products',
  alterations: [
    alter(ProductsTable).addColumn('description', field.string()),
    alter(ProductsTable).dropColumn('legacy_notes'),
    alter(ProductsTable).renameColumn('qty', 'stock'),
  ],
};`;

  readonly alterSql = `alter table public.products add column if not exists stock integer default 0;
alter table public.products drop column if exists legacy_notes;
alter table public.products rename column qty to stock;`;
}
